# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'FirebaseTutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseTutorial

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'


  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  target 'FirebaseTutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseTutorialUITests' do
    # Pods for testing
  end

end
